<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>Canvas_Render.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="FontData.cs~RF19028c2f.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Canvas_Render.ico" />
  </ItemGroup>

</Project>